### ISSUE TITLE
TypeError: sslChecker is not a function

### ISSUE THREAD

**Issue by EMANSO** [dyaa/ssl-checker#44]
Hello,

I've tried it following your instructions.

@2.0.4 works fine, however @2.0.5 gives the following error:

TypeError: sslChecker is not a function
    at Object.<anonymous> (/workspace/myproject/app.js:324:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Cheers.

**Comment by mskian** [comment]
facing same error

**Comment by ixuz** [comment]
I get the same issue with 2.0.5, but 2.0.4 is ok.

**Comment by dunklesToast** [comment]
Since this is an ES6 Module you need to use `const sslChecker = require('ssl-checker').default` to require it properly
